server:
  port: 9090

spring:
  application:
    name: stp-gateway
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:nacos:minio.yaml
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
