server:
  port: 8089

spring:
  application:
    name: stp-coupon-service
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:nacos:shared-common.yaml
      - optional:nacos:sentinel.yaml
      - optional:nacos:minio.yaml
      - optional:nacos:shared-seata.yaml?group=SEATA_GROUP
      - optional:file:.env[.properties]
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        username: ${NACOS_USER_NAME}
        password: ${NACOS_USER_PASSWORD}
        refresh-enabled: true
        file-extension: yaml
      server-addr: ${HOST}:8848

stp:
  jdbc:
    mapper-locations: classpath*:mapper/coupon/**/*.xml
    type-aliases-package: com.summit.stp.coupon.infrastructure.persistence.po
