spring:
  application:
    name: stp-toolbox-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stp-project?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 500ms

server:
  port: 8085

mybatis-plus:
  mapper-locations: classpath*:mapper/toolbox/**/*.xml
  type-aliases-package: com.summit.stp.toolbox.infrastructure.persistence.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto