server:
  port: 8085

spring:
  application:
    name: stp-toolbox-service
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:nacos:minio.yaml
  cloud:
    nacos:
      config:
        shared-dataids: minio.yaml,jdbc.yaml,redis.yaml,queue.yaml
        import-check:
          enabled: false
        username: nacos
        password: nacos
        refresh-enabled: true
        file-extension: yaml

mybatis-plus:
  mapper-locations: ${stp.jdbc.mapper-locations}
  type-aliases-package: ${stp.jdbc.type-aliases-package}
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

stp:
  jdbc:
    mapper-locations: classpath*:mapper/toolbox/**/*.xml
    type-aliases-package: com.summit.stp.toolbox.infrastructure.persistence.po
