server:
  port: 8085

spring:
  application:
    name: stp-toolbox-service
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:file:.env[.properties]
      - optional:nacos:shared-common.yaml
      - optional:nacos:minio.yaml
      - optional:nacos:shared-seata.yaml?group=SEATA_GROUP
      - optional:nacos:sentinel.yaml
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        username: ${NACOS_USER_NAME}
        password: ${NACOS_USER_PASSWORD}
        refresh-enabled: true
        file-extension: yaml
      server-addr: ${HOST}:8848


stp:
  jdbc:
    mapper-locations: classpath*:mapper/toolbox/**/*.xml
    type-aliases-package: com.summit.stp.toolbox.infrastructure.persistence.po
