server:
  port: 8083

spring:
  application:
    name: stp-post-service
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:nacos:minio.yaml
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        refresh-enabled: true
        file-extension: yaml
      server-addr: 127.0.0.1:8848


stp:
  jdbc:
    mapper-locations: classpath*:mapper/post/**/*.xml,classpath*:mapper/rank_board/**/*.xml
    type-aliases-package: com.summit.stp.post.infrastructure.persistence.po,com.summit.stp.rank_board.infrastructure.persistence.po
