server:
  port: 8086

spring:
  application:
    name: stp-comment-service
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:nacos:minio.yaml
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
        refresh-enabled: true
        file-extension: yaml


stp:
  jdbc:
    mapper-locations: classpath*:mapper/comment/**/*.xml
    type-aliases-package: com.summit.stp.comment.infrastructure.persistence.po
