server:
  port: 9090

spring:
  application:
    name: stp-gateway
  config:
    import:
      - optional:nacos:jdbc.yaml
      - optional:nacos:sentinel.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:queue.yaml
      - optional:nacos:shared-common.yaml
      - optional:nacos:minio.yaml
      - optional:file:.env[.properties]
      - optional:nacos:shared-seata.yaml?group=SEATA_GROUP
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
      server-addr: ${HOST}:8848
stp:
  auth:
    jwt:
      secret-key: ${STP_AUTH_JWT_SECRET_KEY}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
